# Use postgres/example user/password credentials
version: '3.1'

volumes:
    personal-web-db:
        driver: local

services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: personal_web
    volumes:
      - personal-web-db:/var/lib/postgresql/data
    ports:
      - 5432:5432